"""Production Migrations

Revision ID: 727745508567
Revises: 
Create Date: 2020-03-20 01:39:41.057664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727745508567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full', sa.String(length=200), nullable=False),
    sa.Column('short', sa.String(length=8), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('shortcodes')
    # ### end Alembic commands ###
